################################################
# FreeBSD 15 - loader.conf (stabil + gehärtet)
################################################

# ZFS Root
zfs_load="YES"
vfs.root.mountfrom="zfs:zroot/ROOT/default"

# GEOM-Label-Noise reduzieren
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"

# Firewall früh laden
pf_load="YES"
pflog_load="YES"

# Intel Grafik (KMS)
i915kms_load="YES"

# Boot-Optik
loader_logo="beastiebw"

# Sicherheit: Kernel-Debugger deaktivieren
debug.debugger_on_panic="0"
kern.debugger_on_panic="0"
hw.kbd.reset_on_panic="1"

