clear_tmp_enable="YES"
hostname="terminal-AXR-01"
keymap="de.noacc.kbd"

# Netzwerk
ifconfig_em0="DHCP"
ifconfig_em0_ipv6="inet6 accept_rtadv"

# Dienste
sshd_enable="YES"
ntpd_enable="YES"
ntpd_sync_on_start="YES"
local_unbound_enable="YES"
powerd_enable="YES"
moused_enable="YES"

# Crashdumps
dumpdev="AUTO"

# ZFS
zfs_enable="YES"

# Grafik / Desktop
kld_list="i915kms"
dbus_enable="YES"
sddm_enable="YES"

# Firewall
pf_enable="YES"
pflog_enable="YES"
pf_rules="/etc/pf.conf"

# securelevel deaktiviert (pf-kompatibel!)
#kern_securelevel_enable="YES"
#kern_securelevel="1"

